import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Main from './main'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mood List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
 
        <Main/>
      


    </div>
  )
}

export default Home
